/// Flutter icons PLLIcon
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CubeIcon
///      fonts:
///       - asset: fonts/CubeIcon.ttf
///
/// 
///
library;
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class CubeIcon {
  CubeIcon._();

  static const _kFontFam = 'CubeIcon';
  static const String? _kFontPkg = null;

  static const IconData oll_black = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pll_black = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
